# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PUNTO_A3.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
import sys
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(778, 523)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 10, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(20, 90, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setMaxVisibleItems(3)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 140, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(20, 170, 501, 311))
        self.graphicsView.setObjectName("graphicsView")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(530, 310, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(530, 250, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(530, 290, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(530, 270, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(530, 330, 241, 131))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        ruta_base = os.path.dirname(os.path.abspath(__file__))
        ruta_logo = os.path.join(ruta_base, "ecci.jpg")
        self.label_8.setPixmap(QtGui.QPixmap(ruta_logo))
        self.label_8.setScaledContents(True)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(170, 140, 401, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setText("")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 778, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.layout_grafica = QtWidgets.QVBoxLayout(self.graphicsView)
        self.figura = plt.figure()
        self.canvas = FigureCanvas(self.figura)
        self.layout_grafica.addWidget(self.canvas)
        self.comboBox.currentIndexChanged.connect(self.actualizar_robot)
        self.actualizar_robot()  # Para mostrar el robot inicial al cargar la aplicación

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TIPOS DE ROBOTS"))
        self.label_2.setText(_translate("MainWindow", "SELECCIONE EL ROBOT A CONSULTAR"))
        self.comboBox.setItemText(0, _translate("MainWindow", "CARTESIANO"))
        self.comboBox.setItemText(1, _translate("MainWindow", "ESFERICO"))
        self.comboBox.setItemText(2, _translate("MainWindow", "CILINDRICO"))
        self.label_3.setText(_translate("MainWindow", "El Robot tiene"))
        self.label_6.setText(_translate("MainWindow", "ELECTIVA DE ROBOTICA"))
        self.label_5.setText(_translate("MainWindow", "UNIVERSIDAD ECCI"))
        self.label_4.setText(_translate("MainWindow", "BRAYAN CAMILO ROMERO BERNAL"))
        self.label_7.setText(_translate("MainWindow", "JOHAN SEBASTIAN FAJARDO PIRAQUIVE"))

    def actualizar_robot(self):
        seleccion = self.comboBox.currentText()
        # Obtenemos la ruta de la carpeta donde está este script
        ruta_base = os.path.dirname(os.path.abspath(__file__))
        # 2. Lógica de Articulaciones (Static Text / QLabel)
        # Suponiendo que tu QLabel de información se llama label_info
        if seleccion == "CARTESIANO":
            info = "3 Articulaciones Tipo: Prismáticas (PPP)"
            img_path = os.path.join(ruta_base, "cartesiano.jpg")
        elif seleccion == "CILINDRICO":
            info = "3 Articulaciones Tipo: 1 Rotacional, 2 Prismáticas (RPP)"
            img_path = os.path.join(ruta_base, "cilindrico.png")
        elif seleccion == "ESFERICO":
            info = "3 Articulaciones Tipo: 2 Rotacionales, 1 Prismática (RRP)"
            img_path = os.path.join(ruta_base, "esferico.jpg")
        else:
            return

        self.label_9.setText(info) # Actualiza el Static Text

        # 3. Visualizar Diagrama en el Objeto Axes (Matplotlib)
        try:
            import matplotlib.image as mpimg
            self.figura.clear()
            ax = self.figura.add_subplot(111)
            
            img = mpimg.imread(img_path)
            ax.imshow(img)
            ax.axis('off') # Quita los números de los ejes para que se vea solo el diagrama
            
            self.canvas.draw()
        except Exception as e:
            print(f"No se pudo cargar la imagen: {e}")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
