# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PUNTO_A4.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(819, 567)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(540, 340, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(540, 280, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(540, 320, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(540, 300, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(540, 370, 261, 111))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_7.setPixmap(QtGui.QPixmap("ecci.jpg"))
        self.label_7.setScaledContents(True)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 10, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 60, 501, 441))
        self.graphicsView.setObjectName("graphicsView")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(530, 60, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(530, 130, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(540, 200, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.horizontalScrollBar.setGeometry(QtCore.QRect(530, 90, 271, 21))
        self.horizontalScrollBar.setMinimum(1)
        self.horizontalScrollBar.setMaximum(100)
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.horizontalScrollBar_2 = QtWidgets.QScrollBar(self.centralwidget)
        self.horizontalScrollBar_2.setGeometry(QtCore.QRect(530, 160, 271, 21))
        self.horizontalScrollBar_2.setMinimum(10)
        self.horizontalScrollBar_2.setMaximum(1000)
        self.horizontalScrollBar_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_2.setObjectName("horizontalScrollBar_2")
        self.horizontalScrollBar_3 = QtWidgets.QScrollBar(self.centralwidget)
        self.horizontalScrollBar_3.setGeometry(QtCore.QRect(530, 230, 271, 21))
        self.horizontalScrollBar_3.setMinimum(1)
        self.horizontalScrollBar_3.setMaximum(24)
        self.horizontalScrollBar_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_3.setObjectName("horizontalScrollBar_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 819, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.layout_grafica = QtWidgets.QVBoxLayout(self.graphicsView)
        self.figura = plt.figure()
        self.canvas = FigureCanvas(self.figura)
        self.layout_grafica.addWidget(self.canvas)
        self.horizontalScrollBar.valueChanged.connect(self.graficar_dinamico)
        self.horizontalScrollBar_2.valueChanged.connect(self.graficar_dinamico)
        self.horizontalScrollBar_3.valueChanged.connect(self.graficar_dinamico)
        self.graficar_dinamico()  # Graficar inicialmente con valores por defecto  

       

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "ELECTIVA DE ROBOTICA"))
        self.label_5.setText(_translate("MainWindow", "UNIVERSIDAD ECCI"))
        self.label_4.setText(_translate("MainWindow", "BRAYAN CAMILO ROMERO BERNAL"))
        self.label_3.setText(_translate("MainWindow", "JOHAN SEBASTIAN FAJARDO PIRAQUIVE"))
        self.label.setText(_translate("MainWindow", "CARGA Y DESCARGA DE UN CONDENSADOR"))
        self.label_2.setText(_translate("MainWindow", "RESISTENCIA"))
        self.label_8.setText(_translate("MainWindow", "CAPACITANCIA"))
        self.label_9.setText(_translate("MainWindow", "VOLTAJE"))

    def graficar_dinamico(self):
        try:
            R=self.horizontalScrollBar.value() * 1000
            C=self.horizontalScrollBar_2.value() * 1e-6   
            V=self.horizontalScrollBar_3.value()
            tau = R * C # Constante de tiempo
            t = np.linspace(0, 5 * tau, 1000) # Rango de 5 veces tau para ver carga completa

            # 2. Fórmulas
            v_carga = V * (1 - np.exp(-t / tau))
            v_descarga = V * np.exp(-t / tau)

            # 3. Dibujar en el Axes
            self.figura.clear()
            ax = self.figura.add_subplot(111)
            
            ax.plot(t, v_carga, label='Carga', color='blue', lw=2)
            ax.plot(t, v_descarga, label='Descarga', color='red', linestyle='--')
            
            ax.set_title(f"Dinámica RC (Tau = {tau:.3f}s)")
            ax.set_xlabel("Tiempo (s)")
            ax.set_ylabel("Voltaje (V)")
            ax.set_ylim(-0.5, V + 1)
            ax.grid(True, alpha=0.3)
            ax.legend()
            
            self.canvas.draw()
        except Exception as e:
            print(f"Error: {e}")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
