# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PUNTO_A2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
import matplotlib.pyplot as plt
import math
import numpy as np
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 517)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 10, 441, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 60, 491, 411))
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(520, 230, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(520, 200, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(520, 180, 231, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(520, 290, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(520, 310, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(520, 270, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(520, 330, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(520, 360, 261, 111))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        ruta_base = os.path.dirname(os.path.abspath(__file__))
        ruta_logo = os.path.join(ruta_base, "ecci.jpg")
        self.label_7.setPixmap(QtGui.QPixmap(ruta_logo))
        self.label_7.setScaledContents(True)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(520, 120, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(520, 60, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setObjectName("label_9")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(520, 80, 91, 31))
        self.textEdit.setObjectName("textEdit")  
        self.textEdit.setFont(font)   
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(520, 140, 91, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_2.setFont(font)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.layout_grafica = QtWidgets.QVBoxLayout(self.graphicsView)
        self.figura = plt.figure()
        self.canvas = FigureCanvas(self.figura)
        self.layout_grafica.addWidget(self.canvas)
        self.pushButton.clicked.connect(self.graficar)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "GRAFICAR OPERACIONES TRIGONOMETRICAS"))
        self.pushButton.setText(_translate("MainWindow", "GRAFICAR"))
        self.comboBox.setItemText(0, _translate("MainWindow", "SENO"))
        self.comboBox.setItemText(1, _translate("MainWindow", "COSENO"))
        self.comboBox.setItemText(2, _translate("MainWindow", "TANGENTE"))
        self.comboBox.setItemText(3, _translate("MainWindow", "SECANTE"))
        self.comboBox.setItemText(4, _translate("MainWindow", "COSECANTE"))
        self.comboBox.setItemText(5, _translate("MainWindow", "COTANGENTE"))
        self.label_2.setText(_translate("MainWindow", "SELECCIONE LA FUNCION"))
        self.label_3.setText(_translate("MainWindow", "JOHAN SEBASTIAN FAJARDO PIRAQUIVE"))
        self.label_4.setText(_translate("MainWindow", "BRAYAN CAMILO ROMERO BERNAL"))
        self.label_5.setText(_translate("MainWindow", "UNIVERSIDAD ECCI"))
        self.label_6.setText(_translate("MainWindow", "ELECTIVA DE ROBOTICA"))
        self.label_8.setText(_translate("MainWindow", "VALOR MAXIMO"))
        self.label_9.setText(_translate("MainWindow", "VALOR MINIMO"))

    def graficar(self):
        try:
            # 1. Obtener valores de los TextEdits
            valor_min = float(self.textEdit.toPlainText())
            valor_max = float(self.textEdit_2.toPlainText())
            
            # 2. Preparar datos
            x = np.linspace(valor_min, valor_max, 1000)
            seleccion = self.comboBox.currentText()
            
            # 3. Limpiar y crear eje
            self.figura.clear()
            ax = self.figura.add_subplot(111)
            
            # 4. Lógica de selección
            if seleccion == "SENO":
                y = np.sin(x)
            elif seleccion == "COSENO":
                y = np.cos(x)
            elif seleccion == "TANGENTE": 
                y = np.tan(x)
                ax.set_ylim(-10, 10)
            elif seleccion == "SECANTE": 
                y = 1 / np.cos(x)
                ax.set_ylim(-10, 10)
            elif seleccion == "COSECANTE": 
                y = 1 / np.sin(x)
                ax.set_ylim(-10, 10)
            elif seleccion == "COTANGENTE": 
                y = 1 / np.tan(x)
                ax.set_ylim(-10, 10)

            # 5. Renderizar
            ax.plot(x, y, label=seleccion, color='red')
            ax.axhline(0, color='black', lw=1)
            ax.grid(True)
            ax.legend()
            self.canvas.draw()
            
        except ValueError:
            print("Error: Ingresa números válidos en los campos de texto.")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
