# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PUNTO_A5.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog  # <--- AGREGA ESTA LÍNEA
import cv2
import sys
import os
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(818, 526)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 10, 391, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 70, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(350, 60, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(20, 120, 551, 361))
        self.graphicsView.setObjectName("graphicsView")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(580, 250, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(580, 210, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(580, 190, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(580, 270, 221, 141))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        ruta_base = os.path.dirname(os.path.abspath(__file__))
        ruta_logo = os.path.join(ruta_base, "ecci.jpg")
        self.label_7.setPixmap(QtGui.QPixmap(ruta_logo))
        self.label_7.setScaledContents(True)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(580, 230, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 818, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.procesar_contornos)
        self.layout_grafica = QtWidgets.QVBoxLayout(self.graphicsView)
        self.figura = plt.figure()
        self.canvas = FigureCanvas(self.figura)
        self.layout_grafica.addWidget(self.canvas)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "OBTENER CONTORNO DE UNA IMAGEN"))
        self.label_2.setText(_translate("MainWindow", "CLIC PARA ELEGIR LA IMAGEN"))
        self.pushButton.setText(_translate("MainWindow", "CARGAR IMAGEN"))
        self.label_6.setText(_translate("MainWindow", "ELECTIVA DE ROBOTICA"))
        self.label_3.setText(_translate("MainWindow", "JOHAN SEBASTIAN FAJARDO PIRAQUIVE"))
        self.label_5.setText(_translate("MainWindow", "UNIVERSIDAD ECCI"))
        self.label_4.setText(_translate("MainWindow", "BRAYAN CAMILO ROMERO BERNAL"))

    def procesar_contornos(self):
        ruta, _ = QFileDialog.getOpenFileName(None, "Buscar Imagen", "", "Imágenes (*.jpg *.png *.jpeg)")
        
        if ruta:
            img = cv2.imread(ruta)
            gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
            
            # --- AQUÍ ESTÁN LOS CAMBIOS ---
            # 1. Usamos THRESH_BINARY_INV para invertir colores (fondo negro, líneas blancas)
            _, thresh = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY_INV)
            
            # 2. Usamos RETR_TREE para encontrar contornos internos
            contornos, _ = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
            # ------------------------------

            img_contornos = cv2.drawContours(img.copy(), contornos, -1, (0, 255, 0), 2)
            img_rgb = cv2.cvtColor(img_contornos, cv2.COLOR_BGR2RGB)

            self.figura.clear()
            ax = self.figura.add_subplot(111)
            ax.imshow(img_rgb)
            # Ahora el número de contornos debería ser mucho mayor (letras, ejes, etc.)
            ax.set_title(f"Contornos encontrados: {len(contornos)}")
            ax.axis('off')
            self.canvas.draw()

        else:
            print("No se seleccionó ninguna imagen.")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
