# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PUNTO_B1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
import sys

try:
    from gpiozero import AngularServo
    from gpiozero.pins.lgpio import LGPIOFactory
    factory = LGPIOFactory()
    
    # Ajuste de pulsos para mayor rango y estabilidad
    # min_pulse_width=0.0005 (0.5ms) y max_pulse_width=0.0025 (2.5ms)
    SERVO_1 = AngularServo(12, min_angle=0, max_angle=180, 
                           min_pulse_width=0.0005, max_pulse_width=0.0025, 
                           pin_factory=factory)
    SERVO_2 = AngularServo(13, min_angle=0, max_angle=180, 
                           min_pulse_width=0.0005, max_pulse_width=0.0025, 
                           pin_factory=factory)
except (ImportError, IOError):
    print("Error: Hardware no detectado.")
    SERVO_1 = SERVO_2 = None



class Ui_MainWindow(object):
    def __init__(self):
        self.ultimo_angulo_1 = -1
        self.ultimo_angulo_2 = -1

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 320)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 0, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 501, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(20, 100, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(20, 150, 481, 31))
        self.horizontalSlider.setMaximum(180)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(290, 100, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 210, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 190, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 230, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(280, 180, 221, 141))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        ruta_base = os.path.dirname(os.path.abspath(__file__))
        ruta_logo = os.path.join(ruta_base, "ecci.jpg")
        self.label_7.setPixmap(QtGui.QPixmap(ruta_logo))
        self.label_7.setScaledContents(True)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 250, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 519, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.horizontalSlider.valueChanged.connect(self.servos)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "CONTROL DE DOS SERVOMOTORES"))
        self.label_2.setText(_translate("MainWindow", "INGRESE QUE SERVO QUIERE USAR (SERVO 1, SERVO 2)"))
        self.label_4.setText(_translate("MainWindow", "JOHAN SEBASTIAN FAJARDO PIRAQUIVE"))
        self.label_5.setText(_translate("MainWindow", "UNIVERSIDAD ECCI"))
        self.label_6.setText(_translate("MainWindow", "BRAYAN CAMILO ROMERO BERNAL"))
        self.label_8.setText(_translate("MainWindow", "ELECTIVA DE ROBOTICA"))

    def servos(self):
        servo_name = self.textEdit.toPlainText().strip().upper()
        nuevo_angulo = self.horizontalSlider.value()
        
        # Umbral de movimiento para evitar vibración (2 grados)
        umbral = 5

        if servo_name == "SERVO 1" and SERVO_1:
            # Solo mueve si el cambio es mayor al umbral
            if abs(nuevo_angulo - self.ultimo_angulo_1) >= umbral:
                SERVO_1.angle = nuevo_angulo
                self.ultimo_angulo_1 = nuevo_angulo
                self.label_3.setText(f"Servo 1: {nuevo_angulo}°")
        
        elif servo_name == "SERVO 2" and SERVO_2:
            if abs(nuevo_angulo - self.ultimo_angulo_2) >= umbral:
                SERVO_2.angle = nuevo_angulo
                self.ultimo_angulo_2 = nuevo_angulo
                self.label_3.setText(f"Servo 2: {nuevo_angulo}°")



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
